#################################
# NETWORK
#################################

bind 0.0.0.0
port 6379
protected-mode yes
tcp-keepalive 60
timeout 0

#################################
# SECURITY
#################################

requirepass YOUR_STRONG_PASSWORD

#################################
# MEMORY
#################################

# Không giới hạn trong Redis
# Giới hạn bằng Docker thay vì Redis
maxmemory 0

# Không bao giờ evict key
maxmemory-policy noeviction

#################################
# PERSISTENCE
#################################

# AOF (BẮT BUỘC)
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Snapshot backup layer
save 900 1
save 300 10
save 60 10000

#################################
# PERFORMANCE
#################################

databases 16
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes

#################################
# LOGGING
#################################

loglevel notice